services:
  proxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    hostname: proxymanager
    container_name: proxymanager
    ports:
      - '80:80'
      - '443:443'
      - '127.0.0.1:81:81'
    volumes:
      - ./proxymanager/data:/data
      - ./proxymanager/letsencrypt:/etc/letsencrypt
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet
    external: true